.\" qemuconf-import(1) manual page
.\" See LICENSE file for copyright and license details.
.Dd August 8, 2023
.Dt QEMUCONF-IMPORT 1
.Os
.\" ==================================================================
.Sh NAME
.Nm qemuconf-import
.Nd make qemuconf file from currently running qemu instance
.\" ==================================================================
.Sh SYNOPSIS
.Nm
.\" ==================================================================
.Sh DESCRIPTION
.Nm
creates configuration file for
.Xr qemuconf 1
from currently running
.Xr qemu 1
instance.
.\" ==================================================================
.Sh SEE ALSO
.Xr qemu 1 ,
.Xr qemuconf 1
.\" ==================================================================
.Sh AUTHORS
.An Enno T. Boland Aq Mt eb@s01.de
.\" vim: cc=72 tw=70
.\" End of file.
