.Dd August 11, 2023
.Dt QEMUCONF 1
.Os qemuconf @VERSION@
.Sh NAME
.Nm qemuconf
.Nd simple qemu launcher with configuration files support
.Sh SYNOPSIS
.Nm
.Op Fl nv
.Op Fl q Ar exec
.Aq Ar config
.Op Fl - Ar qemu args ...
.Sh DESCRIPTION
.Nm
executes
.Xr qemu 1
with arguments compiled from a
.Aq Ar config
configuration file.
.Pp
The options are as follows:
.Bl -tag -width XXXXXXX
.It Fl n
Dry-run.  Print the produced argument list to stdout, instead of
executing.  Useful for diagnostic purposes.
.It Fl q Ar exec
Set the default qemu binary.  This option may be overwritten by the
.Aq Ar qemubin
option in the configuration file.
.It Fl v
Print version and exit.
.El
.Sh EXAMPLES
Lets say we have the following configuration file:
.Bd -literal -offset indent
#
# /etc/qemuconf.d/generic.conf: configuration file for qemuconf(1)
#

qemubin /usr/bin/qemu-system-x86_64
cwd     /var/qemu/generic
smp     2
m       1024
enable-kvm
drive:
  if      virtio
  file    hda.img
net nic:
  vlan    0
  model   virtio
  macaddr 82:82:9D:AF:F0:1C
net user:
  vlan    0
vnc 127.0.0.1:1

# End of file.
.Ed
.Pp
This configuration file will be translated by
.Nm
into the following command:
.Bd -literal -offset indent
/usr/bin/qemu-system-x86_64 -smp 2 -m 1024 -enable-kvm \\
  -drive if=virtio,file=hda.img \\
  -net nic,vlan=0,model=virtio,macaddr=82:82:9D:AF:F0:1C \\
  -net user,vlan=0 \\
  -vnc 127.0.0.1:1
.Ed
.Pp
The
.Aq Ar cwd
option instructs
.Nm
to
.Xr chdir 2
into
.Pa /var/qemu/generic
before executing a
.Xr qemu 1
instance.
.Sh SEE ALSO
.Xr qemuconf-import 1 ,
.Xr qemu 1
.Sh AUTHORS
.Nm
was written by
.An Enno Boland Aq Mt eb@s01.de .
.Pp
The current implementation was reworked by
.An Alexandr Savca Aq Mt alexandr.savca@gmail.com .
