.Dd August 08, 2023
.Dt QEMUCONF-IMPORT 1
.Os qemuconf @VERSION@
.Sh NAME
.Nm qemuconf-import
.Nd make qemuconf file from currently running qemu instance
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
creates configuration file for
.Xr qemuconf 1
from currently running
.Xr qemu 1
instance.
.Sh AUTHORS
.An Enno T. Boland Aq Mt eb@s01.de
.Sh SEE ALSO
.Xr qemuconf 1 ,
.Xr qemu 1
