#!/bin/sh
# See LICENSE file for copyright and license details.

# shellcheck shell=sh disable=2086

mkconfig() {
	#EXE=$(readlink $1/exe)
	_CWD=$(readlink $1/cwd)
	echo "cwd ${_CWD}"

	_LASTOPT=
	printf "qemubin "
	tr "\0" "\n" < "$1/cmdline" | while read -r _ARG; do
		if [ -z "${_ARG%%-*}" ]; then
			[ "${_LASTOPT}" ] && echo
			printf "%s" "${_ARG#-}"
			_LASTOPT=1
			continue
		fi
		_LASTOPT=

		if [ "${_ARG##*,*}" ]; then
			echo " ${_ARG}"
			continue
		fi
		echo :

		IFS=,
		for i in ${_ARG}; do
			printf "\t%s\n" "${i}";
		done
		unset IFS
	done
}

for _PROC in /proc/*/exe; do
	case $(readlink ${_PROC}) in
	*/qemu-*|*/qemu) :        ;;
	              *) continue ;;
	esac

	_CONF=$(mkconfig ${_PROC%/*})
	echo "--------"
	echo "${_CONF}"
	echo "--------"

	printf "Save as (enter to skip): "
	read -r _NAME
	[ "${_NAME}" ] && echo "${_CONF}" > "${_NAME}"
done

# End of file.
